-- Special Masses (weddings, requiems, feasts) share the plan table with Sundays.
-- Several may fall on one day, so the date is no longer unique; a single
-- Sunday plan per date is enforced in the app.
ALTER TABLE `MassPlan` ADD COLUMN `kind` ENUM('SUNDAY', 'WEDDING', 'REQUIEM', 'FEAST', 'OTHER') NOT NULL DEFAULT 'SUNDAY',
    ADD COLUMN `venue` VARCHAR(191) NULL;

CREATE INDEX `MassPlan_kind_date_idx` ON `MassPlan`(`kind`, `date`);

DROP INDEX `MassPlan_date_key` ON `MassPlan`;

-- Parts sung only at special Masses.
ALTER TABLE `MassPlanItem` MODIFY `part` ENUM('ENTRANCE', 'PENITENTIAL', 'KYRIE', 'GLORIA', 'RESPONSORIAL_PSALM', 'GOSPEL_ACCLAMATION', 'GOSPEL_PROCESSION', 'CREED', 'OFFERTORY', 'PREPARATION_OF_GIFTS', 'SANCTUS', 'MYSTERY_OF_FAITH', 'GREAT_AMEN', 'OUR_FATHER', 'SIGN_OF_PEACE', 'AGNUS_DEI', 'COMMUNION', 'ANIMA_CHRISTI', 'THANKSGIVING', 'RECESSIONAL', 'MARIAN_HYMN', 'RITE_OF_MARRIAGE', 'SIGNING_OF_REGISTER', 'FINAL_COMMENDATION') NOT NULL;

ALTER TABLE `SongProposalItem` MODIFY `part` ENUM('ENTRANCE', 'PENITENTIAL', 'KYRIE', 'GLORIA', 'RESPONSORIAL_PSALM', 'GOSPEL_ACCLAMATION', 'GOSPEL_PROCESSION', 'CREED', 'OFFERTORY', 'PREPARATION_OF_GIFTS', 'SANCTUS', 'MYSTERY_OF_FAITH', 'GREAT_AMEN', 'OUR_FATHER', 'SIGN_OF_PEACE', 'AGNUS_DEI', 'COMMUNION', 'ANIMA_CHRISTI', 'THANKSGIVING', 'RECESSIONAL', 'MARIAN_HYMN', 'RITE_OF_MARRIAGE', 'SIGNING_OF_REGISTER', 'FINAL_COMMENDATION') NOT NULL;
